### ISSUE TITLE
What machine arch were these compiled on x86_64 or arm (M1)?

### ISSUE THREAD

**Issue by cjappl** [thinkski/toolchains#12]
First off THANK YOU, this repo is extremely helpful.

Trying to build my own version of them, as I need a few tweaks, but running into some issues on the `bison` step of `ct-ng`.

Wondering if the machine you originally created these with was Intel or M1.

**Comment by cjappl** [comment]
@thinkski pinging you on this again, in case you didn't see!

**Comment by hiszpanski** [comment]
@cjappl Builds were on Intel

**Comment by cjappl** [comment]
Thanks @thinkski !

Feel free to close this ticket. I am trying to wrestle with ct-ng to build an m1->rpi3 crosstools and it's giving me grief. These builds you've produced even running through rosetta are a godsend! Thanks for putting them up :)
