### ISSUE TITLE
arm-linux-gnueabihf-gcc for ArmV7

### ISSUE THREAD

**Issue by jkelleyrtp** [thinkski/toolchains#3]
Currently, hardfloat is not supported for ArmV7, but is for ArmV8, but the RPI0-W supports V7-hard float. Is it possible to get this supported?

**Comment by EarthyOrange** [comment]
I am also looking for `AArch32 target with hard float (arm-none-linux-gnueabihf)` on MacOS.

Thank you!

**Comment by hiszpanski** [comment]
Good idea. Not sure when I'll get a chance to work on it, but if it's important to you, [buy me a coffee](https://www.buymeacoffee.com/thinkski) and I'll see how far the caffeine gets me one evening.

**Comment by EarthyOrange** [comment]
@thinkski Can you please take a look at https://github.com/thinkski/osx-arm-linux-toolchains/pull/5?

**Comment by hiszpanski** [comment]
Done in #5
