### ISSUE TITLE
Automatic building

### ISSUE THREAD

**Issue by jamesy0ung** [thinkski/toolchains#8]
Can you use an automated system to push new builds out frequently?

**Comment by hiszpanski** [comment]
This would be nice, although I don't have the bandwidth or incentive to implement this in the foreseeable future. If anyone would like to take this on, perhaps via TravisCI or CircleCI, please let me know.

**Comment by aholtzma-am** [comment]
Can you post your crosstool-ng recipe? I will make a GitHub action to do the build with that.

**Comment by VladutLP** [comment]
Hey @thinkski, can you help us out?

**Comment by hiszpanski** [comment]
The crosstool-ng build configuration is included within the releases (see the build.log.bz2 file).
