### ISSUE TITLE
hello,can you send me the .config file

### ISSUE THREAD

**Issue by liufulj** [thinkski/toolchains#9]
i use the macos big sur and crosstool-ng 1.24.0 build the arm-unknow-linux-gnueabi ,it if faild. can you set you .config to me ? i need build the kernel 4.19 

log:
[ALL  ]    Unknown target in --with-cpu=arm
[ERROR]    make[1]: *** [Makefile:4183: configure-gcc] Error 1
[ALL  ]    make[1]: Leaving directory '/Volumes/e-mac/ct-ng-arm-unknown-linux-gnueabi/.build/arm-unknown-linux-gnueabi/build/build-cc-gcc-core-pass-1'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@684]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc/gcc.sh@209]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 14:04.00)

**Comment by hiszpanski** [comment]
The contents of the `.config` are available within the build log contained within each .tar.gz.
